# Generated by Django 4.2 on 2023-04-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P1", "Urgent"),
                            ("P2", "Important"),
                            ("P3", "Secondary"),
                        ],
                        default="P3",
                        max_length=2,
                    ),
                ),
                ("due_date", models.DateField()),
            ],
        ),
    ]
