# Generated by Django 4.2 on 2023-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todomain", "0004_remove_taggeditem_tag_delete_tag_delete_taggeditem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "todo",
                    models.ManyToManyField(
                        blank=True, related_name="tag", to="todomain.todo"
                    ),
                ),
            ],
            options={"db_table": "category",},
        ),
    ]
