# Generated by Django 4.2 on 2023-04-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todomain", "0006_tag_taggeditem_delete_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="todo",
            field=models.ManyToManyField(related_name="tag", to="todomain.todo"),
        ),
        migrations.DeleteModel(name="TaggedItem",),
    ]
