# Generated by Django 4.2 on 2023-04-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todomain", "0007_tag_todo_delete_taggeditem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="todo",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tag", to="todomain.todo"
            ),
        ),
    ]
