# Generated by Django 4.2 on 2023-04-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tags", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taggeditem",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag",
                to="contenttypes.contenttype",
            ),
        ),
    ]
